// Mocks generated by Mockito 5.0.17 from annotations
// in todo/test/mock_tests/todo_repository_mock_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:todo/src/entities/todo.dart' as _i2;
import 'package:todo/src/requests/todo_create.dart' as _i3;
import 'package:todo/src/requests/todo_delete.dart' as _i5;
import 'package:todo/src/requests/todo_get_detail.dart' as _i6;
import 'package:todo/src/requests/todo_get_list.dart' as _i7;
import 'package:todo/src/requests/todo_update.dart' as _i8;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeTodo_0 extends _i1.Fake implements _i2.Todo {}

/// A class which mocks [TodoCreateRequest].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoCreateRequest extends _i1.Mock implements _i3.TodoCreateRequest {
  MockTodoCreateRequest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Todo> execute(Map<String, dynamic>? variables) =>
      (super.noSuchMethod(Invocation.method(#execute, [variables]),
              returnValue: Future<_i2.Todo>.value(_FakeTodo_0()))
          as _i4.Future<_i2.Todo>);
  @override
  _i4.Future<_i2.Todo> run() => (super.noSuchMethod(Invocation.method(#run, []),
          returnValue: Future<_i2.Todo>.value(_FakeTodo_0()))
      as _i4.Future<_i2.Todo>);
}

/// A class which mocks [TodoDeleteRequest].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoDeleteRequest extends _i1.Mock implements _i5.TodoDeleteRequest {
  MockTodoDeleteRequest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> execute(Map<String, dynamic>? variables) =>
      (super.noSuchMethod(Invocation.method(#execute, [variables]),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
  @override
  _i4.Future<bool> run() => (super.noSuchMethod(Invocation.method(#run, []),
      returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
}

/// A class which mocks [TodoGetDetailRequest].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoGetDetailRequest extends _i1.Mock
    implements _i6.TodoGetDetailRequest {
  MockTodoGetDetailRequest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Todo> execute(Map<String, dynamic>? variables) =>
      (super.noSuchMethod(Invocation.method(#execute, [variables]),
              returnValue: Future<_i2.Todo>.value(_FakeTodo_0()))
          as _i4.Future<_i2.Todo>);
  @override
  _i4.Future<_i2.Todo> run() => (super.noSuchMethod(Invocation.method(#run, []),
          returnValue: Future<_i2.Todo>.value(_FakeTodo_0()))
      as _i4.Future<_i2.Todo>);
}

/// A class which mocks [TodoGetListRequest].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoGetListRequest extends _i1.Mock
    implements _i7.TodoGetListRequest {
  MockTodoGetListRequest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Todo>> execute(Map<String, dynamic>? variables) =>
      (super.noSuchMethod(Invocation.method(#execute, [variables]),
              returnValue: Future<List<_i2.Todo>>.value(<_i2.Todo>[]))
          as _i4.Future<List<_i2.Todo>>);
  @override
  _i4.Future<List<_i2.Todo>> run() =>
      (super.noSuchMethod(Invocation.method(#run, []),
              returnValue: Future<List<_i2.Todo>>.value(<_i2.Todo>[]))
          as _i4.Future<List<_i2.Todo>>);
}

/// A class which mocks [TodoUpdateRequest].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoUpdateRequest extends _i1.Mock implements _i8.TodoUpdateRequest {
  MockTodoUpdateRequest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Todo> execute(Map<String, dynamic>? variables) =>
      (super.noSuchMethod(Invocation.method(#execute, [variables]),
              returnValue: Future<_i2.Todo>.value(_FakeTodo_0()))
          as _i4.Future<_i2.Todo>);
  @override
  _i4.Future<_i2.Todo> run() => (super.noSuchMethod(Invocation.method(#run, []),
          returnValue: Future<_i2.Todo>.value(_FakeTodo_0()))
      as _i4.Future<_i2.Todo>);
}
