name: todo
description: Module for retrieving and modifying user todos.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  network:
    path: ../../network

dev_dependencies:
  lint: ^1.7.2
  test: ^1.16.0
