name: todo
description: Module for retrieving and modifying user todos.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  network:
    path: ../../network

dev_dependencies:
  build_runner: ^2.1.7
  graphql: ^5.0.0
  lint: ^1.7.2
  mockito: ^5.0.17
  test: ^1.16.0
