name: itodo

packages:
  - modules/**
  - modules/repositories/**
  - '*'

analyze:
  run: melos exec -- flutter analyze .
  description: Analyze all packages

scripts:
  test:
    run: melos exec --dir-exists="test" -- flutter test --coverage
    description: Run all tests with coverage
