name: itodo
description: Your friendly app for creating TODOs.

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  auth:
    path: modules/repositories/auth
  equatable: ^2.0.3
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  network:
    path: modules/network
  purifier:
    path: modules/purifier
  todo:
    path: modules/repositories/todo
  user:
    path: modules/repositories/user

dev_dependencies:
  flutter_test:
    sdk: flutter

  graphql: ^5.0.0
  lint: 1.7.2
  mockito: ^5.0.17
  test: ^1.16.0

flutter:
  uses-material-design: true
