name: itodo
description: Your friend-app for creating TODOs.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.7.2

flutter:
  uses-material-design: true
