// Mocks generated by Mockito 5.0.17 from annotations
// in user/test/mock_tests/user_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:user/src/entities/user.dart' as _i2;
import 'package:user/src/requests/user_create.dart' as _i3;
import 'package:user/src/requests/user_detail.dart' as _i6;
import 'package:user/src/requests/user_update.dart' as _i5;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeUser_0 extends _i1.Fake implements _i2.User {}

/// A class which mocks [UserCreateRequest].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserCreateRequest extends _i1.Mock implements _i3.UserCreateRequest {
  MockUserCreateRequest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.User> execute(Map<String, dynamic>? variables) =>
      (super.noSuchMethod(Invocation.method(#execute, [variables]),
              returnValue: Future<_i2.User>.value(_FakeUser_0()))
          as _i4.Future<_i2.User>);
  @override
  _i4.Future<_i2.User> run() => (super.noSuchMethod(Invocation.method(#run, []),
          returnValue: Future<_i2.User>.value(_FakeUser_0()))
      as _i4.Future<_i2.User>);
}

/// A class which mocks [UserUpdateRequest].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserUpdateRequest extends _i1.Mock implements _i5.UserUpdateRequest {
  MockUserUpdateRequest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.User> execute(Map<String, dynamic>? variables) =>
      (super.noSuchMethod(Invocation.method(#execute, [variables]),
              returnValue: Future<_i2.User>.value(_FakeUser_0()))
          as _i4.Future<_i2.User>);
  @override
  _i4.Future<_i2.User> run() => (super.noSuchMethod(Invocation.method(#run, []),
          returnValue: Future<_i2.User>.value(_FakeUser_0()))
      as _i4.Future<_i2.User>);
}

/// A class which mocks [UserDetailRequest].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserDetailRequest extends _i1.Mock implements _i6.UserDetailRequest {
  MockUserDetailRequest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.User> execute(Map<String, dynamic>? variables) =>
      (super.noSuchMethod(Invocation.method(#execute, [variables]),
              returnValue: Future<_i2.User>.value(_FakeUser_0()))
          as _i4.Future<_i2.User>);
  @override
  _i4.Future<_i2.User> run() => (super.noSuchMethod(Invocation.method(#run, []),
          returnValue: Future<_i2.User>.value(_FakeUser_0()))
      as _i4.Future<_i2.User>);
}
