name: network
description: Module for core network functionalities.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  graphql: ^5.0.0
  meta: ^1.7.0

dev_dependencies:
  lint: ^1.7.2
  test: ^1.16.0
