name: view_router
description: A new Flutter package project.
version: 1.0.0

publish_to: "none"

environment:
  sdk: ">=2.14.4 <3.0.0"
  flutter: ">=2.5.3"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: 1.7.2

flutter: null
