
name: Test when push to master branch

on:
  push:
    branches: [ master ]

jobs:
  test_and_push:
    name: Run tests and upload coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.5.3'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get
      
      - name: Activate melos
        run: dart pub global activate melos

      - name: Analyze project source
        run: melos run analyze

      - name: Run tests using melos
        run: melos run test
      
      - uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
